version: '3'

services:
  tapo-exporter:
    image: tapo-exporter
    volumes:
       - ./tapo.yaml:/app/tapo.yaml:ro
    networks:
      - monitoring
    ports:
      - 9333:9333
    environment:
      - TAPO_EMAIL=$TAPO_EMAIL
      - TAPO_PASSWORD=$TAPO_PASSWORD
      - PORT=9333