{
 "title": "Energy monitoring",
 "description": "Tapo %model",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "eur_per_kWh", "label": "EUR/kWh", "query": "${VAR_EUR_PER_KWH}" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(tapo_%model_today_energy_wh, job)"
    }
   },
   {
    "name": "machine",
    "label": "Machine",
    "query": {
     "query": "label_values(tapo_%model_today_energy_wh, machine)"
    }
   },
   {
    "name": "rooms",
    "label": "Rooms",
    "query": {
     "query": "label_values(tapo_%model_today_energy_wh, room)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Todays usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (room) (tapo_%model_today_energy_wh{job=\"$job\", machine=\"$machine\", room=~\"$rooms\"})",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Todays price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (room)(tapo_%model_today_energy_wh{job=\"$job\", machine=\"$machine\", room=~\"$rooms\"}/1000*$eur_per_kWh)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Number of plugs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tapo_%model_device_count{job=\"$job\", machine=\"$machine\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Current draw",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (room)(tapo_%model_power_consumption_w{job=\"$job\", machine=\"$machine\", room=~\"$rooms\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monthly use",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (room) (tapo_%model_month_energy_wh{job=\"$job\", machine=\"$machine\", room=~\"$rooms\"})",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Months price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (room)(tapo_%model_month_energy_wh{job=\"$job\", machine=\"$machine\", room=~\"$rooms\"}/1000*$eur_per_kWh)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "EUR/kWh",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$eur_per_kWh", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current draw ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "tapo_%model_power_consumption_w{job=\"$job\", machine=\"$machine\", room=~\"$rooms\"}",
     "legendFormat": "{{room}}"
    }
   ]
  }
 ]
}